server:
   port: 9001
debug: false # 可以查看自动配置启用禁用了哪些配置
# spring:
#    data:
#       mongodb:
         # mongodb://name:pass@localhost:27017/test
         # 不指定数据库，一般是默认是test数据库
#          uri: mongodb://127.0.0.1:27017/test 